minimumReleaseAge: 1440 # 1 day
savePrefix: '' # saveExact equivalent
verifyDepsBeforeRun: error
engineStrict: true
allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
minimumReleaseAgeExclude:
  - eslint@10.8.1
strictDepBuilds: true
blockExoticSubdeps: true
trustPolicy: no-downgrade
